sudo: required
language: java

services:
  - docker

before_install:
  - mvn -N io.takari:maven:wrapper
  - mvn clean package

install:


before_script:

script:
  - docker build -t shtunder/pipeline-test:0.1 .



after_script:


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shtunder/pipeline-test:0.1

after_failure:

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: docker-pipeline-test
  env: Dockerpipelinetest-env
  bucket_name: elasticbeanstalk-eu-north-1-953923509938
  bucket_path: docker-pipeline-test
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY