sudo: required
language: java
services:
  - docker

script:
  - mvn clean package
  - docker build -t shtunder/pipeline-test:0.1 .


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shtunder/pipeline-test:0.1

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: docker-pipeline-test
  env: Dockerpipelinetest-env
  bucket_name: elasticbeanstalk-eu-north-1-953923509938
  bucket_path: docker-pipeline-test
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY